### ISSUE TITLE
Add a license and code of conduct

### ISSUE THREAD

**Issue by saadkadhi** [xg5-simon/CrowdStrike2TH#1]
It would be nice to add a license and a code of conduct such as 
https://github.com/TheHive-Project/TheHive/blob/master/LICENSE and 
https://github.com/TheHive-Project/TheHive/blob/master/code_of_conduct.md

**Comment by xg5-simon** [comment]
Thanks for the great suggestion @saadkadhi . GNU Affero General Public License v3.0 and a Code of Conduct has been added.
